stages:
  data_engineering:
    cmd: kedro run --pipeline data_engineering
    deps:
      - src/nba/pipelines/data_engineering
      - conf/base/parameters.yml
      - data/01_raw/games.csv
    outs:
      - data/02_intermediate/games_limpios.parquet
    metrics:
      - data/06_reporting/validation_report.json:
          cache: false

  classification:
    cmd: kedro run --pipeline classification
    deps:
      - src/nba/pipelines/classification
      - data/05_model_input/model_input_classification.parquet
    outs:
      - data/07_model_output/classification/best_classification_model.pkl
    metrics:
      - data/07_model_output/classification/classification_report.json:
          cache: false

  regression:
    cmd: kedro run --pipeline regression
    deps:
      - src/nba/pipelines/regression
      - data/03_primary/games_teams_details.parquet
    outs:
      - data/06_models/local_strength_model.pkl
    metrics:
      - data/08_reporting/model_report.json:
          cache: false